name: sulamerica
channels:
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - numpy
  - pandas
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn 
  - xlrd
  - flake8
  - autopep8
  - pip:
    - .

